name: UcuzUcus Bot

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  send-flights:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Bot
        run: node bot.js
